function productGallery(folder, filenames) {
    return filenames.map(filename => `assets/img/catalogo-rolders/${folder}/${filename}`);
}

const ORBIX_GALLERY = [
    "WhatsApp Image 2026-10-05 at 12.59.32 PM (1).jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.32 PM (2).jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.32 PM (3).jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.32 PM (4).jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.32 PM.jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.33 PM (1).jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.33 PM (2).jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.33 PM.jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.34 PM (1).jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.34 PM.jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.35 PM (1).jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.35 PM (2).jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.35 PM.jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.36 PM (1).jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.36 PM (2).jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.36 PM.jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.37 PM (1).jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.37 PM (2).jpeg",
    "WhatsApp Image 2026-10-05 at 12.59.37 PM.jpeg"
].map(filename => `assets/img/catalogo-rolders/Orbix/${filename}`);

const PRODUCTS_DATA = [
    {
        id: "ecoride-pro-350",
        name: "EcoRide PRO",
        category: "patinetes",
        brand: "rolders",
        badge: "URBANO",
        image: "assets/img/catalogo-rolders/EcoRide/6.png",
        coverImage: "assets/img/catalogo-rolders/Portadas/1.png",
        accent: "#f97824",
        coverNotice: "La portada indica SOLD OUT; consulta existencias actualizadas.",
        gallery: productGallery("EcoRide", ["2.png", "4.png", "6.png", "7.png", "9.png"]),
        description: "Scooter urbano con autonomía de 25 a 30 km, velocidad máxima de 25 km/h y tres modos de manejo.",
        keywords: ["ecoride", "pro", "urbano", "plegable", "350w", "scooter"],
        features: ["Autonomía: 25–30 km", "Velocidad máxima: 25 km/h", "Motor: 350 W", "Peso máximo soportado: 120 kg", "Llanta: 8,5″ Honey Comb", "Resistencia: IP54", "Freno: disco trasero", "Peso: 14 kg", "Display EcoRide", "Modos: Eco, Standard y Sport"]
    },
    {
        id: "starglide-600",
        name: "StarGlide 600",
        category: "patinetes",
        brand: "rolders",
        badge: "CITY RIDE",
        image: "assets/img/catalogo-rolders/StarGlide/2.png",
        coverImage: "assets/img/catalogo-rolders/Portadas/2.png",
        accent: "#70cf50",
        coverNotice: "La portada indica SOLD OUT; consulta existencias actualizadas.",
        gallery: productGallery("StarGlide", ["1.png", "2.png", "3.png", "4.png", "5.png"]),
        description: "Scooter urbano con motor de 600 W, autonomía de 40 a 45 km y suspensión delantera y trasera.",
        keywords: ["starglide", "star glide", "urbano", "ciudad", "600w", "scooter"],
        features: ["Autonomía: 40–45 km", "Velocidad máxima: 40 km/h", "Motor: 600 W (1 motor)", "Peso máximo soportado: 120 kg", "Llanta: 10″ sellomatic", "Resistencia: IP54", "Frenos: discos delantero y trasero", "Peso: 26 kg", "Display LED", "Modos: Eco, Standard y Turbo", "Suspensión delantera y trasera"]
    },
    {
        id: "orbix-1000",
        name: "Orbix",
        category: "patinetes",
        brand: "rolders",
        badge: "ALTO DESEMPEÑO",
        image: "assets/img/catalogo-rolders/Portadas/5.jpeg",
        coverImage: "assets/img/catalogo-rolders/Portadas/5.jpeg",
        accent: "#ef263a",
        gallery: ORBIX_GALLERY,
        description: "Scooter de alto desempeño con motor de 1000 W, autonomía de 60 a 70 km y velocidad máxima de 60 km/h.",
        keywords: ["orbix", "potencia", "doble motor", "scooter", "luces"],
        features: ["Autonomía: 60–70 km", "Velocidad máxima: 60 km/h", "Motor: 1000 W", "Peso máximo soportado: 150 kg", "Llanta: 10″ sellomatic", "Resistencia: IPX4", "Frenos: discos delantero y trasero", "Peso: 28 kg", "Display LED", "Modos: Walk, Eco, Standard y Turbo", "Suspensión Monoshock delantera y trasera"]
    },
    {
        id: "rocket-roll-800",
        name: "Rocket Roll 800",
        category: "patinetes",
        brand: "rolders",
        badge: "ADVENTURE",
        image: "assets/img/catalogo-rolders/RocketRoll/2.png",
        coverImage: "assets/img/catalogo-rolders/Portadas/3.png",
        accent: "#9150f8",
        gallery: productGallery("RocketRoll", ["1.png", "2.png", "3.png", "4.png", "5.png"]),
        description: "Scooter con motor de 800 W, autonomía de 70 a 75 km y suspensión Monoshock delantera y trasera.",
        keywords: ["rocket roll", "rocketroll", "800w", "scooter", "off road"],
        features: ["Autonomía: 70–75 km", "Velocidad máxima: 45 km/h", "Motor: 800 W (1 motor)", "Peso máximo soportado: 150 kg", "Llanta: 10″ sellomatic Pro", "Resistencia: IP54", "Frenos: discos delantero y trasero", "Peso: 29 kg", "Display LED", "Modos: Eco, Confort, Standard y Turbo", "Suspensión Monoshock delantera y trasera"]
    },
    {
        id: "rocket-roll-1600",
        name: "Rocket Roll 1600",
        category: "patinetes",
        brand: "rolders",
        badge: "ALTO DESEMPEÑO",
        image: "assets/img/catalogo-rolders/RocketRoll/1.png",
        coverImage: "assets/img/catalogo-rolders/Portadas/4.png",
        accent: "#f0444d",
        gallery: productGallery("RocketRoll", ["1.png", "2.png", "3.png", "4.png", "5.png"]),
        description: "Scooter de doble motor y 800 W por motor, con autonomía de 70 a 75 km y velocidad máxima de 45 km/h.",
        keywords: ["rocket roll", "rocketroll", "1600w", "45kmh", "45 km/h", "scooter", "off road"],
        features: ["Autonomía: 70–75 km", "Velocidad máxima: 45 km/h", "Motor: 800 W (2 motores)", "Peso máximo soportado: 150 kg", "Llanta: 10″ sellomatic Pro", "Resistencia: IP54", "Frenos: discos delantero y trasero", "Peso: 32 kg", "Display LED", "Modos: Eco, Confort, Standard y Turbo", "Suspensión Monoshock delantera y trasera"]
    },
    {
        id: "rep-pastillas-freno",
        name: "Pastillas de freno",
        category: "frenos",
        brand: "multimarca",
        consultFor: ["xiaomi", "zwheel", "minca", "rolders", "segway", "scooterco"],
        badge: "MULTIMARCA",
        image: "assets/img/brake-pads.svg",
        imageAlt: "Ilustración de referencia de pastillas de freno; confirmar compatibilidad antes de pedir",
        description: "La forma de la pastilla cambia según el modelo. Envía una foto para validar cuál necesita tu scooter.",
        keywords: ["pastillas", "freno", "frenos", "ceramica", "xiaomi", "zwheel", "minca", "segway"],
    },
    {
        id: "rep-llantas",
        name: "Llantas y neumáticos",
        category: "llantas",
        brand: "multimarca",
        consultFor: ["xiaomi", "zwheel", "minca", "rolders", "segway", "scooterco"],
        badge: "MULTIMARCA",
        image: "assets/img/tire.svg",
        imageAlt: "Ilustración de referencia de llanta; confirmar medida y compatibilidad antes de pedir",
        description: "Cuéntanos la marca, el modelo y la medida impresa en la rueda para identificar la llanta correcta.",
        keywords: ["llanta", "neumatico", "rueda", "tubeless", "xiaomi", "zwheel", "minca", "segway"],
    },
    {
        id: "rep-cargadores",
        name: "Cargadores y baterías",
        category: "baterias",
        brand: "multimarca",
        consultFor: ["xiaomi", "zwheel", "minca", "rolders", "segway", "scooterco"],
        badge: "MULTIMARCA",
        image: "assets/img/charger.svg",
        imageAlt: "Ilustración de referencia de cargador; confirmar voltaje y conector antes de pedir",
        description: "Confirma el voltaje y el tipo de conector con nuestro equipo antes de elegir cargador o batería.",
        keywords: ["cargador", "bateria", "baterias", "conector", "xiaomi", "zwheel", "minca", "segway"],
    }
];
